system: "base24"
name: "Galaxy"
author: "FredHappyface (https://github.com/fredHappyface)"
variant: "dark"
palette:
  base00: "1C2836"
  base01: "000000"
  base02: "555555"
  base03: "6E6E6E"
  base04: "888888"
  base05: "A1A1A1"
  base06: "BBBBBB"
  base07: "FFFFFF"
  base08: "F9555F"
  base09: "FDBA29"
  base0A: "FDF029"
  base0B: "20AF89"
  base0C: "1E9EE6"
  base0D: "589CF5"
  base0E: "934D95"
  base0F: "7C2A2F"
  base10: "383838"
  base11: "1C1C1C"
  base12: "FA8B8E"
  base13: "FFFF55"
  base14: "34BB99"
  base15: "3978BB"
  base16: "589CF5"
  base17: "E75598"
overrides:
  statusline_a_bg: # base03
    color: "6E6E6E"
  statusline_a_fg: # base00
    color: "1C2836"
  statusline_b_bg: # base10
    color: "383838"
  statusline_b_fg: # base05
    color: "A1A1A1"
  statusline_c_bg: # base01
    color: "000000"
  statusline_c_fg: # base05
    color: "A1A1A1"
