package generator

import (
	"fmt"
	"io"

	"github.com/curtbushko/flair/internal/domain"
	"github.com/curtbushko/flair/internal/ports"
)

// Gtk implements ports.Generator for the GTK target.
// It writes a gtk.css file with @define-color declarations followed by
// widget selector rules from a GtkTheme.
type Gtk struct{}

// NewGtk returns a new GTK generator.
func NewGtk() *Gtk {
	return &Gtk{}
}

// Name returns the target name for this generator.
func (g *Gtk) Name() string {
	return "gtk"
}

// DefaultFilename returns the default output filename for GTK CSS.
func (g *Gtk) DefaultFilename() string {
	return "gtk.css"
}

// Generate writes the GtkTheme as a GTK CSS stylesheet to w. The mapped
// argument must be a *ports.GtkTheme; a type assertion failure returns a
// *domain.GenerateError. Output consists of a comment header, @define-color
// declarations, then widget selector rules.
func (g *Gtk) Generate(w io.Writer, mapped ports.MappedTheme) error {
	theme, ok := mapped.(*ports.GtkTheme)
	if !ok {
		return &domain.GenerateError{
			Target:  "gtk",
			Message: fmt.Sprintf("expected *ports.GtkTheme, got %T", mapped),
		}
	}

	if err := writeGtkHeader(w); err != nil {
		return &domain.GenerateError{
			Target:  "gtk",
			Message: "failed to write header",
			Cause:   err,
		}
	}

	if err := writeDefineColors(w, theme.Colors); err != nil {
		return &domain.GenerateError{
			Target:  "gtk",
			Message: "failed to write @define-color declarations",
			Cause:   err,
		}
	}

	if err := writeGtkWidgetRules(w, theme.Rules); err != nil {
		return &domain.GenerateError{
			Target:  "gtk",
			Message: "failed to write widget rules",
			Cause:   err,
		}
	}

	return nil
}

// writeGtkHeader writes a GTK-specific CSS comment header.
func writeGtkHeader(w io.Writer) error {
	_, err := fmt.Fprint(w, "/* GTK theme generated by flair */\n\n")
	return err
}

// writeDefineColors writes @define-color declarations for all color
// definitions in the GtkTheme.
func writeDefineColors(w io.Writer, colors []ports.GtkColorDef) error {
	for _, cd := range colors {
		if _, err := fmt.Fprintf(w, "@define-color %s %s;\n", cd.Name, cd.Value); err != nil {
			return err
		}
	}

	return nil
}

// writeGtkWidgetRules writes GTK CSS widget rules with selector { property: value; }
// formatting. A blank line separates each rule from the previous block.
func writeGtkWidgetRules(w io.Writer, rules []ports.CSSRule) error {
	for _, rule := range rules {
		// Blank line before each rule to separate from previous block.
		if _, err := fmt.Fprintf(w, "\n%s {\n", rule.Selector); err != nil {
			return err
		}

		for _, prop := range rule.Properties {
			if _, err := fmt.Fprintf(w, "  %s: %s;\n", prop.Property, prop.Value); err != nil {
				return err
			}
		}

		if _, err := fmt.Fprint(w, "}\n"); err != nil {
			return err
		}
	}

	return nil
}
