package generator

import (
	"fmt"
	"io"

	"github.com/curtbushko/flair/internal/domain"
	"github.com/curtbushko/flair/internal/ports"
)

// Qss implements ports.Generator for the Qt Style Sheet (QSS) target.
// It writes a style.qss file with widget selector rules using literal
// hex color values. Unlike GTK CSS, QSS does not support @define-color
// or CSS custom properties -- all colors are inlined directly.
type Qss struct{}

// NewQss returns a new QSS generator.
func NewQss() *Qss {
	return &Qss{}
}

// Name returns the target name for this generator.
func (q *Qss) Name() string {
	return "qss"
}

// DefaultFilename returns the default output filename for QSS.
func (q *Qss) DefaultFilename() string {
	return "style.qss"
}

// Generate writes the QssTheme as a Qt Style Sheet to w. The mapped
// argument must be a *ports.QssTheme; a type assertion failure returns a
// *domain.GenerateError. Output consists of a comment header followed by
// widget selector rules with literal hex color values.
func (q *Qss) Generate(w io.Writer, mapped ports.MappedTheme) error {
	theme, ok := mapped.(*ports.QssTheme)
	if !ok {
		return &domain.GenerateError{
			Target:  "qss",
			Message: fmt.Sprintf("expected *ports.QssTheme, got %T", mapped),
		}
	}

	if err := writeQssHeader(w); err != nil {
		return &domain.GenerateError{
			Target:  "qss",
			Message: "failed to write header",
			Cause:   err,
		}
	}

	if err := writeQssWidgetRules(w, theme.Rules); err != nil {
		return &domain.GenerateError{
			Target:  "qss",
			Message: "failed to write widget rules",
			Cause:   err,
		}
	}

	return nil
}

// writeQssHeader writes a QSS-specific comment header.
func writeQssHeader(w io.Writer) error {
	_, err := fmt.Fprint(w, "/* Qt Style Sheet generated by flair */\n")
	return err
}

// writeQssWidgetRules writes QSS widget rules with selector { property: value; }
// formatting. A blank line separates each rule from the previous block.
func writeQssWidgetRules(w io.Writer, rules []ports.CSSRule) error {
	for _, rule := range rules {
		// Blank line before each rule to separate from previous block.
		if _, err := fmt.Fprintf(w, "\n%s {\n", rule.Selector); err != nil {
			return err
		}

		for _, prop := range rule.Properties {
			if _, err := fmt.Fprintf(w, "  %s: %s;\n", prop.Property, prop.Value); err != nil {
				return err
			}
		}

		if _, err := fmt.Fprint(w, "}\n"); err != nil {
			return err
		}
	}

	return nil
}
